#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" >> /var/www/html/index.html
sudo sed -i "60i\ \t add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx start
