#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
apt-get update
apt-get -y install haproxy=1.5.\*
sudo echo -e "frontend localnodes
    bind *:80
    mode http
    default_backend nodes

backend nodes
    balance roundrobin
    server web01 34.74.254.207 check port 80
    server web02 34.73.52.215 check port 80" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
