#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the s active IPv4 IPs server
sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sed -i 's/ipv6only=on/ipv6only=off/' /etc/nginx/sites-enabled/default
sudo service nginx start
