#!/usr/bin/env bash
# print a poem using /etc/passwd
i=1
while [[ $i -le $(cat /etc/passwd | wc -l) ]]
do
    lina=$(cat /etc/passwd | head -n $i | tail -n 1)
    IFS=':'
    set $lina
    echo "The user $1 is part of the $4 gang, lives in $6 and rides $7. $3's place is protected by the passcode $2, more info about the user here: $5"
    ((i++))
done
