#!/usr/bin/env bash
# displays bad luck at 4, good luck at 8 and holberton school on other iterations

i=1
while [[ $i -le 10 ]]
do
    if [[ $i -eq 4 ]]
    then
	echo 'bad luck'
    elif [[ $i -eq 8 ]] ; then
	echo 'good luck'
    else
	echo 'Holberton School'
    fi
    ((i++))
done
