#!/usr/bin/env bash
# displays bad luck at 4, good luck at 8 and holberton school on other iterations

i=1
while [[ $i -le 20 ]]
do
    echo $i
    case $i in
	4)
	echo 'bad luck from China'
	;;
	9)
	echo 'good luck from Japan'
	;;
	12)
	echo 'good luck from Italy'
	;;
    esac
    ((i++))
done
