#!/usr/bin/env bash
# displays bad luck at 4, good luck at 8 and holberton school on other iterations

i=1
while [[ $i -le 20 ]]
do
    echo $i
    if [[ $i -eq 4 ]]
    then
	echo 'bad luck from China'
    elif [[ $i -eq 9 ]] ; then
	echo 'good luck from Japan'
    elif [[ $i -eq 17 ]] ; then
	echo 'good luck from Italy'
    fi
    ((i++))
done
